### ISSUE TITLE
I2C breadboard PNG update

### ISSUE THREAD

**Issue by taartspi** [Pi4J/pi4j-jbang#4]
The CS pin should be connected to 3.3v  This is required to enable the I2C interface.   This must be connected to 3.3 volts before the VCC pin is connected to 3.3v.  The connection order is documented in the Datasheet, not sure if you want to make any mention of this detail in this location, failure to do this could be frustrating debug.            Also, the SDO pin determines the chips I2C address.  If this example remains with 0x77 as the default address the SDO pin should be connected to 3.3v                                     I decided I would not attempt this artwork update, although I should update my environment to do so.

**Comment by FDelporte** [comment]
Thanks & fixed!
